### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by vicb** [Turbo87/igc-parser#127]
IGC lat/lon format is DDmm.mmm so the minimum value that could be represented in decimal degree is 0.0000166666...
So I think it would be great to round lat/lon values to 5 digits: 6.452566666666667 would become 6.45257.

I could implement this change if we agree on that.

**Comment by Turbo87** [comment]
why should we round any values? that would actually take some precision away.

also, there are extensions in the file format that allow for increased precision, so we can't assume that five digits is enough

**Comment by vicb** [comment]
As explained we wouldn't loose any precision because 1e-5 is less than the actual precision (0.000016666....). 

However this is not accounting for the extensions as I was not aware of them. However rounding to 5 digits would give a precision of roughly 1 meter which is more than enough given GPS precision.

Feel free to close the issue if you think it's useless. I can do that as a post processing step.

Thanks

**Comment by Turbo87** [comment]
I essentially just don't know why you would want to round the values. if this is just about final formatting for showing the values to  users then this should definitely be done after the initial parsing step.

**Comment by vicb** [comment]
It's useless bits on the wire when my app fetch the tracks.
Again feel free to close.
