### ISSUE TITLE
Bug in handling of B Record Extensions

### ISSUE THREAD

**Issue by tyddynonn** [Turbo87/igc-parser#192]
Nice parser! but unfortunately there's a bug in the handling of B record extensions.

Take this I record and B record, taken from a real flight:

I043638FXA3941ENL4246GSP4749TRT
B0902005623773N00403165WA025980260600607015906352

The I Record specifies ENL will be at positions 39-41 in the B record, so start at position 39 for 3 characters

slice(39,42) in the B record gives 701. But the correct ENL value from this record is in fact 070.

The position values in the I record are one-based, not zero-based as used in slice
ref https://xp-soaring.github.io/igc_file_format/igc_format_2008.html#link_3.4 - see '...taking the first B in the line as byte one'

So the correct value is obtained by using slice(38,41) in the B record.

Fix is to change line 498 & 499 to subtract 1 from the start & end values.

**Comment by Turbo87** [comment]
ouch, don't know how that slipped by... would you mind opening a pull request to fix the issue? :)

**Comment by tyddynonn** [comment]
These things happen 😊
PR is there

Best 

Chris

**Comment by Turbo87** [comment]
resolved by #193
