### ISSUE TITLE
Cannot parse new HFDTEDATE format

### ISSUE THREAD

**Issue by hyperknot** [Turbo87/igc-parser#2]
The new, recommended format used by GPSDump and recent flight software is the `HFDTEDATE` format. igc-parser cannot parse these files.

It does not accept:
```
HFDTEDATE:270418,01
```

It does accept:
```
HFDTE270418
```

Example file: https://drive.google.com/open?id=1m5P4-N_ejU3pbBTDJdYVecc5jaEKMnGc

**Comment by Turbo87** [comment]
hmm interesting, I'll take a look at supporting that unless you want to try fixing it yourself?

**Comment by hyperknot** [comment]
this is quite important part, I guess you are the best person to implement
it
i can share an up to date igc specs

**Comment by hyperknot** [comment]
this is the new specs
https://gitlab.com/xcontest-public/xctrack-public/issues/248#note_71195643
