### ISSUE TITLE
GNSS Altitude (WGS84) - can it be negative at all (not according to the IGC GNSS FR Technical Specification)?

### ISSUE THREAD

**Issue by till213** [Turbo87/igc-parser#361]
Hello,

First of all, thank you for sharing your IGC parser code :) I am currently implementing an "IGC import plugin" for my own little pet project ([SkyDolly ](https://github.com/till213/SkyDolly)- a flight recorder for Flight Simulator 2020) and stumbled over your project. While I was initially tempted to simply extract the string data based on its byte offset (where applicable) I now "borrow" your idea of using regular expresssions - far more conventient ;)

But I wondered whether the last value in the "B record" - specifically: the altitude above the WGS84 elipsoid - can really be negative:

const RE_B = /^B(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\d{3})([NS])(\d{3})(\d{2})(\d{3})([EW])([AV])(-\d{4}|\d{5})(**-\d{4**}|\d{5})/;

Because according to the official specification here:

  https://www.fai.org/sites/default/files/igc_fr_specification_2020-11-25_with_al6.pdf

on page 32 it says:

```
GNSS Alt. - Altitude in metres above the WGS84 ellipsoid, valid characters 0-9
```

(whereas for the "pressure altitude" a negative sign is explicitly allowed and mentioned).

Now there are the following things to consider:

* Your regular expresssion works in any case (even if the "GNSS Altitude" never has a negative sign - and if it does, your code properly parses it)
* I am no expert (not even a real-world pilot like you ;)) when it comes to the WGS84 standard, but I do understand that negative values may actually occur also with this model (also refer to e.g. here: https://stackoverflow.com/questions/12103516/negative-altitude-value#12103768)
* The official IGC specification is also not perfect, it seems, e.g. with regards to the "flight date" in the H record (e.g. it mentions that a comma should separate the flight number from the date, but the given example in the very same document does not have a comma ;))

Anyway, the more I think about it the more I tend to also use your pattern, because it is more robust in any case (should a glider _really_ be flying below the WGS84 elipsoid - and of course there are inaccuracies in GPS modules etc. ;)).

But this gives me a good excuse to also ask the following question, if you allow:

* Like you I also noticed that there is no straight-forward way to detect timestamps "across days": the header only ever mentions one date, and the IGC format does not seem to support updates of the date (the only record that supports "dates" is the H (header) record, so I understand)
* So the only way to detect a "date change" seems to be if a successive timestamp is smaller than the previous one (e.g. wrapping from 23:59:55 to 00:00:00) - so far I figured this out myself as well
* However you seem to be considering "one hour" as an offset, or in other words: only if a given timestamp is at least smaller by one hour than the previous timestamp does your code trigger "date change"

Why is that? The timestamps should be UTC, so not timezone or "winter/summer-time" effects? Shouldn't timestamps be strictly increasing (except for a change of date)? Or what is the reason for this "one hour offset"?

**Comment by Turbo87** [comment]
RE negative GPS altitude: AFAIK there are places e.g. in the Israel dessert that are below 0m elevation. I'm not sure why negative numbers would only be supported for pressure altitude, but not for GPS altitude. I have a faint memory of seeing a couple of IGC files in the past that did indeed have negative altitude values. Generally it's probably better to support it, rather than to error out if a GPS recorder company decides to support it on their side. It's unfortunately very common for these companies to not be 100% spec compliant :-/

RE timestamps: there are quite a few GPS recorders in use and approved that have time shifting issues. in other words: they will record a GPS fix and then another one with a time that is 3sec before the first one. if we didn't have the one hour threshold we would detect these time shifts as UTC date rollovers, which would be incorrect.

**Comment by till213** [comment]
"if we didn't have the one hour threshold we would detect these time shifts as UTC date rollovers, which would be incorrect."

Thank you so much for your reply! Yes, I already thought that this "extra hour" acts as some kind of threshold, for the reason(s) you just explained.

I am quite new to this format (I am implementing this IGC import feature upon request from some user ;)), so I have currently only one IGC "real-world example" at hand.

And yes, I fully agree with your assessment on the various altitude possibilities and other "slightly creative variations", e.g. also in the date + flight number format in the header (H record), which you also already handle correctly (even the official IGC format specification contradicts its own format - in the very same PDF document - with the given example, which does not have a comma between the date and flight number).

By the way I mentioned your project as "third-party product", here:

https://github.com/till213/SkyDolly/blob/feature-igc/THIRD_PARTY.md

(it is currently on a "feature branch" only, but it will soon be merged into main branch :))

**Comment by till213** [comment]
Hello Turbo87,

As mentioned above already your IGC parser code was a great help in implementing my own C++ IGC parser, which got heavily inspired by yours (e.g. to use regular expressions, value validations etc.)

Your contribution is mentioned here:

https://github.com/till213/SkyDolly/blob/main/THIRD_PARTY.md

And within in the application itself (embedded in the “About” dialog):

https://github.com/till213/SkyDolly/blob/main/src/UserInterface/res/text/ThirdParty.md


Thank you so much for providing your IGC parser implementation, it was a great help quickly understanding the IGC format (and its quirks) "by example implementation" :)

Best, Oliver
