### ISSUE TITLE
Additional H records not parsed

### ISSUE THREAD

**Issue by mimomoratti** [Turbo87/igc-parser#485]
# Overview

The IGC Specification allows for "Additional H records" in section: Additional H records
See: https://www.fai.org/sites/default/files/igc_fr_specification_2022_with_al7_2022-1-31.pdf for details

A3.2.6 Additional H records. These are optional and use the Three Letter Codes given in para A7. Additional data may
be follow after the mandatory records. Two additional records (Competition ID and class) are shown below, with extra
spaces for clarity.

H S CID COMPETITION ID : TEXT STRING CR LF
H S CCL COMPETITION CLASS : TEXT STRING CR LF

# Analysis

S is currently not considered as a valid H record it is missing from the VALID_DATA_SOURCES.

# Proposed Fix

* Add S as a valid data source for headers 
* to be strict it should only be considered in CID and CCL headers.

# Workaround

set the lenient option while parsing

**Comment by Turbo87** [comment]
> H S CID COMPETITION ID : TEXT STRING CR LF
> H S CCL COMPETITION CLASS : TEXT STRING CR LF

As far as I am aware the `S` in this context stands for "source" and is just an example in this snippet. You can see in the linked document in section 3.2.5 that only `F` and `O` are valid data source values.
